ALTER TABLE map_catalog ADD COLUMN storage_key VARCHAR(60);
ALTER TABLE map_catalog ALTER COLUMN slug TYPE VARCHAR(60);
ALTER TABLE map_catalog ALTER COLUMN description TYPE VARCHAR(250);
ALTER TABLE map_catalog ALTER COLUMN title TYPE VARCHAR(100);